apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: be-7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-7
  strategy: {}
  template:
    metadata:
        creationTimestamp: null
        labels:
            app: be-7
    spec:
      containers:
      - env:
        image: "172.20.83.35:5000/7:latest"
        imagePullPolicy: "Always"
        name: be-7
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}