apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: be-7
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    nodePort: 30007
  - name: "443"
    port: 443
    targetPort: 443
    nodePort: 30107
  selector:
    app: be-7
  type: NodePort
status:
  loadBalancer: {}

